****************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mprevot <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/12/01 11:18:53 by mprevot           #+#    #+#              #
#    Updated: 2018/11/19 15:40:21 by mprevot          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME=libft.a

CC=gcc

CFLAGS=-g -Wall -Werror -Wextra 

RM=rm -f

SRC= ft_memset.c ft_bzero.c ft_memcpy.c ft_memccpy.c ft_memmovput auteurtakefile
8
mprevot
