#!/bin/bash
while :
do
before=`md5sum /etc/crontab`
sleep 1
after=`md5sum /etc/crontab`
echo "$before"
echo "$after"
echo ""
if [ "$before" != "$after" ]
then
	echo "oh"
	echo "Change detected" | mail -s "olalala :(" root
fi
done
