#ifndef MAIN_HPP
# define MAIN_HPP

#define TIME_ENABLED 1
#define GENERALINFORMATION_ENABLED 1
#define MEMORY_ENABLED 1
#define CPU_ENABLED 1
#define NETWORK_ENABLED 1
#define PONEY_ENABLED 1

#define TIME_POSITION 0
#define GENERALINFORMATION_POSITION 1
#define MEMORY_POSITION 2
#define CPU_POSITION 3
#define NETWORK_POSITION 4
#define PONEY_POSITION 5



#endif